// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: osm_proto3_format/osmformat.proto

module OSMPBF.osmformat;

import google.protobuf;

enum protocVersion = 3008000;

class HeaderBlock
{
    @Proto(1) HeaderBBox bbox = protoDefaultValue!HeaderBBox;
    @Proto(4) string[] requiredFeatures = protoDefaultValue!(string[]);
    @Proto(5) string[] optionalFeatures = protoDefaultValue!(string[]);
    @Proto(16) string writingprogram = protoDefaultValue!string;
    @Proto(17) string source = protoDefaultValue!string;
    @Proto(32) long osmosisReplicationTimestamp = protoDefaultValue!long;
    @Proto(33) long osmosisReplicationSequenceNumber = protoDefaultValue!long;
    @Proto(34) string osmosisReplicationBaseUrl = protoDefaultValue!string;
}

class HeaderBBox
{
    @Proto(1, Wire.zigzag) long left = protoDefaultValue!long;
    @Proto(2, Wire.zigzag) long right = protoDefaultValue!long;
    @Proto(3, Wire.zigzag) long top = protoDefaultValue!long;
    @Proto(4, Wire.zigzag) long bottom = protoDefaultValue!long;
}

class PrimitiveBlock
{
    @Proto(1) StringTable stringtable = protoDefaultValue!StringTable;
    @Proto(2) PrimitiveGroup[] primitivegroup = protoDefaultValue!(PrimitiveGroup[]);
    @Proto(17) int granularity = protoDefaultValue!int;
    @Proto(18) int dateGranularity = protoDefaultValue!int;
    @Proto(19) long latOffset = protoDefaultValue!long;
    @Proto(20) long lonOffset = protoDefaultValue!long;
}

class PrimitiveGroup
{
    @Proto(1) Node[] nodes = protoDefaultValue!(Node[]);
    @Proto(2) DenseNodes dense = protoDefaultValue!DenseNodes;
    @Proto(3) Way[] ways = protoDefaultValue!(Way[]);
    @Proto(4) Relation[] relations = protoDefaultValue!(Relation[]);
    @Proto(5) ChangeSet[] changesets = protoDefaultValue!(ChangeSet[]);
}

class StringTable
{
    @Proto(1) bytes[] s = protoDefaultValue!(bytes[]);
}

class Info
{
    @Proto(1) int version_ = protoDefaultValue!int;
    @Proto(2) long timestamp = protoDefaultValue!long;
    @Proto(3) long changeset = protoDefaultValue!long;
    @Proto(4) int uid = protoDefaultValue!int;
    @Proto(5) uint userSid = protoDefaultValue!uint;
    @Proto(6) bool visible = protoDefaultValue!bool;
}

class DenseInfo
{
    @Proto(1, Wire.none, Yes.packed) int[] version_ = protoDefaultValue!(int[]);
    @Proto(2, Wire.zigzag, Yes.packed) long[] timestamp = protoDefaultValue!(long[]);
    @Proto(3, Wire.zigzag, Yes.packed) long[] changeset = protoDefaultValue!(long[]);
    @Proto(4, Wire.zigzag, Yes.packed) int[] uid = protoDefaultValue!(int[]);
    @Proto(5, Wire.zigzag, Yes.packed) int[] userSid = protoDefaultValue!(int[]);
    @Proto(6, Wire.none, Yes.packed) bool[] visible = protoDefaultValue!(bool[]);
}

class ChangeSet
{
    @Proto(1) long id = protoDefaultValue!long;
}

class Node
{
    @Proto(1, Wire.zigzag) long id = protoDefaultValue!long;
    @Proto(2, Wire.none, Yes.packed) uint[] keys = protoDefaultValue!(uint[]);
    @Proto(3, Wire.none, Yes.packed) uint[] vals = protoDefaultValue!(uint[]);
    @Proto(4) Info info = protoDefaultValue!Info;
    @Proto(8, Wire.zigzag) long lat = protoDefaultValue!long;
    @Proto(9, Wire.zigzag) long lon = protoDefaultValue!long;
}

class DenseNodes
{
    @Proto(1, Wire.zigzag, Yes.packed) long[] id = protoDefaultValue!(long[]);
    @Proto(5) DenseInfo denseinfo = protoDefaultValue!DenseInfo;
    @Proto(8, Wire.zigzag, Yes.packed) long[] lat = protoDefaultValue!(long[]);
    @Proto(9, Wire.zigzag, Yes.packed) long[] lon = protoDefaultValue!(long[]);
    @Proto(10, Wire.none, Yes.packed) int[] keysVals = protoDefaultValue!(int[]);
}

class Way
{
    @Proto(1) long id = protoDefaultValue!long;
    @Proto(2, Wire.none, Yes.packed) uint[] keys = protoDefaultValue!(uint[]);
    @Proto(3, Wire.none, Yes.packed) uint[] vals = protoDefaultValue!(uint[]);
    @Proto(4) Info info = protoDefaultValue!Info;
    @Proto(8, Wire.zigzag, Yes.packed) long[] refs = protoDefaultValue!(long[]);
}

class Relation
{
    @Proto(1) long id = protoDefaultValue!long;
    @Proto(2, Wire.none, Yes.packed) uint[] keys = protoDefaultValue!(uint[]);
    @Proto(3, Wire.none, Yes.packed) uint[] vals = protoDefaultValue!(uint[]);
    @Proto(4) Info info = protoDefaultValue!Info;
    @Proto(8, Wire.none, Yes.packed) int[] rolesSid = protoDefaultValue!(int[]);
    @Proto(9, Wire.zigzag, Yes.packed) long[] memids = protoDefaultValue!(long[]);
    @Proto(10, Wire.none, Yes.packed) MemberType[] types = protoDefaultValue!(MemberType[]);

    enum MemberType
    {
        NODE = 0,
        WAY = 1,
        RELATION = 2,
    }
}
